      - name: Build with Buildozer
        # استخدام الفرع الرئيسي مباشرة لضمان الوصول للمستودع
        uses: kivy/buildozer-action@master
        with:
          workdir: .
          buildozer_version: stable
