name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Buildozer
        uses: ArtemSerebrennkov/buildozer-action@v1
        with:
          python_version: 3.8
          buildozer_version: master
          buildozer_config: buildozer.spec
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: OussamaSat-APK
          path: bin/*.apk

