name: Build APK Stable OussamaSat

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Récupération du code
        uses: actions/checkout@v4

      - name: 2. Build avec Docker (Solution Radical)
        uses: jamescurtin/buildozer-action@v1
        with:
          buildozer_version: stable
          command: buildozer android debug
          repository_display_name: "OussamaSat"

      - name: 3. Téléchargement de l'APK
        uses: actions/upload-artifact@v4
        with:
          name: OussamaSat-Final-APK
          path: bin/*.apk
