name: Build APK Professionnel

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Compilation de l'application OussamaSat
    runs-on: ubuntu-latest

    steps:
      - name: 1. Récupération du code source
        uses: actions/checkout@v4

      - name: 2. Configuration de l'environnement Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 3. Gestion du Cache (Gain de temps)
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: 4. Compilation avec Buildozer (NDK 25b)
        # Utilisation d'une action stable pour éviter les erreurs de licence
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer android debug
          repository_display_name: "OUSSAMA_SAT_PRO"

      - name: 5. Publication du fichier APK final
        uses: actions/upload-artifact@v4
        with:
          name: OussamaSat-Application-Pro
          path: bin/*.apk
